language: python
python: 3.5
sudo: false

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=lint

install:
  - pip install tox

script:
  - tox -e $TOXENV
